### ISSUE TITLE
How to get the file node.pgrk

### ISSUE THREAD

**Issue by Ninecl** [nju-websoft/MBE#3]
Hi! 
Thanks for the code first!
It seems that the file 'node.pgrk' is the necessary file for training. However, when i apply the code on my own dataset, the file doesn't generated although I set --process_data as True.
Based on my backgound knowledge, the file node.pgrk is the page rank score caculated for the nodes in the graph, so shall u provide the associated code that is used for calculating the 'node.pgrk' in your experiments?
Thanks very much!!!!

**Comment by yncui-nju** [comment]
Following [Multi-Hop](https://github.com/salesforce/MultiHopKG/blob/master/data-release.tgz), the PageRank files are generated using the tool (https://github.com/timothyasp/PageRank).

**Comment by Ninecl** [comment]
Thanks very much！
