### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by wenwen19910224** [nju-websoft/MBE#5]
Can you share your thoughts on the design of the dataset for this article?

**Comment by yncui-nju** [comment]
Hi, thank you for your interest in this work! 

We constructed the dataset to primarily simulate three characteristics of real-world scenarios: (i) continuous growth in multiple batches; (ii) emerging entities are more likely to be few-shot, meaning they may only be present in a small number of facts; (iii) some emerging facts may have head and tail entities that are both unseen. As described in Section 4, the dataset is simulated to grow continuously, making popular entities more likely to be in the original KG, while entities with lower degrees are more likely to appear in new batches.
